#if UNITY_EDITOR
namespace AxitUnityTemplate.UI.Classic.Async.Editor
{
    using System.IO;
    using System.Linq;
    using UnityEditor;
    using UnityEngine;

    public class AxitUIEditor
    {
        public const string PREFAB_SCREEN_GUID = "4bddd30fbc719f048b5f9b6179c7c671";
        public const string PREFAB_POPUP_GUID  = "89927398291de5f49bde07326ec1601b";

        [MenuItem("Assets/Create/Axit/UI/Create Classic UI Prefab", false, 10)]
        private static void CreateUiVariant()
        {
            PrefabCreationWindow.ShowWindow();
        }

        [MenuItem("Assets/Create/Axit/UI/Create Classic UI Script", false, 11)]
        private static void OpenScriptCreationWindow()
        {
            ScriptCreationWindow.ShowWindow();
        }

        [MenuItem("Assets/Create/Axit/UI/Create Classic UI Prefab", true)]
        [MenuItem("Assets/Create/Axit/UI/Create Classic UI Script", true)]
        private static bool ValidateCreateActions()
        {
            return !string.IsNullOrEmpty(AxitUIEditor.GetSelectedFolderPath());
        }

        public static string GetSelectedFolderPath()
        {
            return Selection.GetFiltered<Object>(SelectionMode.Assets)
                            .Select(AssetDatabase.GetAssetPath)
                            .FirstOrDefault(AssetDatabase.IsValidFolder);
        }
    }

    public class PrefabCreationWindow : EditorWindow
    {
        private string  lastAutoGeneratedName = "InformationScreen";
        private bool    userChangedName       = false;
        private string  uiName                = "InformationScreen";
        private EUiMode uiMode                = EUiMode.Screen;

        public static void ShowWindow()
        {
            var window = GetWindow<PrefabCreationWindow>("Create Prefab");
            window.minSize = new Vector2(300, 100);
            window.Show();
        }

        private void OnGUI()
        {
            GUILayout.Label("Enter UI Name:", EditorStyles.boldLabel);

            EditorGUI.BeginChangeCheck();
            string newUiName = EditorGUILayout.TextField("Prefab Name", this.uiName);

            if (EditorGUI.EndChangeCheck())
            {
                this.userChangedName = newUiName != this.lastAutoGeneratedName;
                this.uiName          = newUiName;
            }

            EditorGUILayout.HelpBox($"The prefab that will be created is: {this.uiName}View", MessageType.None);

            EditorGUI.BeginChangeCheck();
            var newUiMode = (EUiMode)EditorGUILayout.EnumPopup("UI Mode", this.uiMode);

            if (EditorGUI.EndChangeCheck())
            {
                this.uiMode = newUiMode;

                if (!this.userChangedName)
                {
                    this.uiName                = this.uiMode == EUiMode.Screen ? "InformationScreen" : "InformationPopup";
                    this.lastAutoGeneratedName = this.uiName;
                }
            }

            GUILayout.Space(15);

            if (GUILayout.Button("Create UI Prefab"))
            {
                this.CreatePrefabVariant($"{this.uiName}View", this.uiMode);
                this.Close();
            }

            EditorGUILayout.HelpBox($"The prefab will be created at: {AxitUIEditor.GetSelectedFolderPath()}", MessageType.None);
        }

        private void CreatePrefabVariant(string variantName, EUiMode mode)
        {
            var prefabPath = AssetDatabase.GUIDToAssetPath(mode == EUiMode.Screen ? AxitUIEditor.PREFAB_SCREEN_GUID : AxitUIEditor.PREFAB_POPUP_GUID);

            if (string.IsNullOrEmpty(prefabPath))
            {
                EditorUtility.DisplayDialog("Error", "Could not find UITemplateBase prefab.", "OK");
                return;
            }

            var uiBase = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);

            if (uiBase == null || PrefabUtility.GetPrefabAssetType(uiBase) == PrefabAssetType.NotAPrefab)
            {
                EditorUtility.DisplayDialog("Error", "Invalid prefab selected.", "OK");
                return;
            }

            var selectedFolderPath = AxitUIEditor.GetSelectedFolderPath();

            if (string.IsNullOrEmpty(selectedFolderPath))
            {
                EditorUtility.DisplayDialog("Error", "Please select a valid folder in Project window.", "OK");
                return;
            }

            var variantPath = Path.Combine(selectedFolderPath, variantName + ".prefab");
            variantPath = AssetDatabase.GenerateUniqueAssetPath(variantPath);

            var variantInstance = (GameObject)PrefabUtility.InstantiatePrefab(uiBase);
            PrefabUtility.SaveAsPrefabAsset(variantInstance, variantPath);
            Object.DestroyImmediate(variantInstance);

            Debug.Log($"{variantName} created: {variantPath}");
            AssetDatabase.Refresh();
        }
    }

    public class ScriptCreationWindow : EditorWindow
    {
        private string  lastAutoGeneratedName = "InformationScreen";
        private bool    userChangedName       = false;
        private string  className             = "InformationScreen";
        private EUiMode uiMode                = EUiMode.Screen;

        public static void ShowWindow()
        {
            var window = GetWindow<ScriptCreationWindow>("Create UI Script");
            window.minSize = new Vector2(300, 100);
            window.Show();
        }

        private void OnGUI()
        {
            GUILayout.Label("Enter Class Name:", EditorStyles.boldLabel);

            EditorGUI.BeginChangeCheck();
            string newClassName = EditorGUILayout.TextField("Class Name", this.className);

            if (EditorGUI.EndChangeCheck())
            {
                this.userChangedName = newClassName != this.lastAutoGeneratedName;
                this.className       = newClassName;
            }

            EditorGUILayout.HelpBox($"The script that will be created is: {this.className}View", MessageType.None);

            EditorGUI.BeginChangeCheck();
            var newUiMode = (EUiMode)EditorGUILayout.EnumPopup("UI Mode", this.uiMode);

            if (EditorGUI.EndChangeCheck())
            {
                this.uiMode = newUiMode;

                if (!this.userChangedName)
                {
                    this.className             = this.uiMode == EUiMode.Screen ? "InformationScreen" : "InformationPopup";
                    this.lastAutoGeneratedName = this.className;
                }
            }

            GUILayout.Space(15);

            if (GUILayout.Button("Create UI Script"))
            {
                this.CreateScriptFile();
                this.Close();
            }

            EditorGUILayout.HelpBox($"The script will be created at: {AxitUIEditor.GetSelectedFolderPath()}", MessageType.None);
        }

        private void CreateScriptFile()
        {
            var selectedFolderPath = AxitUIEditor.GetSelectedFolderPath();

            if (string.IsNullOrEmpty(selectedFolderPath))
            {
                EditorUtility.DisplayDialog("Error", "Please select a valid folder in Project window.", "OK");
                return;
            }

            var scriptName = this.className + "View";
            var filePath   = Path.Combine(selectedFolderPath, scriptName + ".cs");
            filePath = AssetDatabase.GenerateUniqueAssetPath(filePath);

            var scriptContent = this.GenerateScriptContent(this.className, this.uiMode);
            File.WriteAllText(filePath, scriptContent);
            AssetDatabase.Refresh();

            Debug.Log($"Script created: {filePath}");
        }

        private string GenerateScriptContent(string baseName, EUiMode mode)
        {
            switch (mode)
            {
                case EUiMode.Screen:
                    return
                        $@"using AxitUnityTemplate.UI.Classic.Async;

public class {baseName}Model : BaseScreenModel
{{
}}

public class {baseName}View : BaseScreenView
{{
}}

public class {baseName}Presenter : BaseScreenPresenter<{baseName}View, {baseName}Model>
{{
    public override string ScreenPath => nameof({baseName}View);
    
    public override void Awake() {{ }}

    public override void OnEnable() {{ }}

    public override void OnDisable() {{ }}

    public override void OnDestroy() {{ }}
}}";
                case EUiMode.Popup:
                    return
                        $@"using AxitUnityTemplate.UI.Classic.Async;

public class {baseName}Model : BasePopupModel
{{
}}

public class {baseName}View : BasePopupView
{{
}}

public class {baseName}Presenter : BasePopupPresenter<{baseName}View, {baseName}Model>
{{
    public override string PopupPath => nameof({baseName}View);
    
    public override void Awake() {{ }}

    public override void OnEnable() {{ }}

    public override void OnDisable() {{ }}

    public override void OnDestroy() {{ }}
}}";
                default:
                    return "Error";
            }
        }
    }

    public enum EUiMode
    {
        Screen,
        Popup
    }
}
#endif